name: flutter_commons
description: Core package
version: 1.0.23+23
publish_to: 'none'
homepage: https://github.com/Anfet/flutter_commons.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  flutter_bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1
  google_api_availability: ^5.0.1
  google_huawei_availability: ^1.4.0
  flutter_svg: any
  sprintf: any

  flutter_logger:
    git:
      url: https://github.com/Anfet/flutter_logger.git
      ref: 'release/0.0.5'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
 
