name: flutter_commons
description: Core package
version: 1.0.26+2
publish_to: 'none'
homepage: https://github.com/Anfet/flutter_commons.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  sprintf: any

  flutter_logger:
    git:
      url: https://github.com/Anfet/flutter_logger.git
      ref: 'release/0.0.5'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
 
