name: flutter_commons
description: Core package
version: 1.0.27+0
publish_to: 'none'
homepage: https://github.com/Anfet/flutter_commons.git

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  sprintf:

  flutter_logger:
    git:
      url: https://github.com/Anfet/flutter_logger.git
      ref: 'release/0.0.7'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
 
